name: Front End Linting

on:
  workflow_call:

jobs:
  front-end-linting:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Web/

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Check Typescript
        run: yarn run type-check

      - name: Run Eslint
        run: yarn run lint

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write ./Web/**/*.{tsx,ts,jsx,js} --config ${{ github.workspace }}/.prettierrc.js
